##########################################
# File: Dockerfile
# Author: Jacob Calvert <jcalvert@jacobncalvert.com>
# Date: Nov-09-2019
# 
# This Dockerfile creates a development environment for 
# building a sample application
#
##########################################

# start from the basic ubuntu image
FROM ubuntu

# install the needed tools in our container
RUN apt-get update && apt-get install build-essential git net-tools -y
