##########################################
# File: Dockerfile
# Author: Jacob Calvert <jcalvert@jacobncalvert.com>
# Date: Nov-08-2019
# 
# This is a basic Dockerfile 
#
##########################################

# start from the basic busybox image
FROM busybox

# put a file in our container
COPY hello-world.txt .
